### ISSUE TITLE
why is there no special coloring for eqnarray, equation, align, etc.

### ISSUE THREAD

**Issue by ivansigmund** [rzukic/zed-latex#3]
When writing latex in zed and write equations they are not highlighted. this is what i get:

<img width="1000" alt="Screenshot 2024-07-11 at 10 56 00" src="https://github.com/rzukic/zed-latex/assets/126872004/aec3e16b-61e5-46c0-8858-e78a01f9596a">

However, the highlighting for the figure environment works just fine, and this is what i would expect:

<img width="976" alt="Screenshot 2024-07-11 at 10 59 45" src="https://github.com/rzukic/zed-latex/assets/126872004/ce9ad07c-774a-4c0f-9ebf-28939172cfa9">

**Comment by lnay** [comment]
The grammar used in this extension is the same as the one in neovim which has much richer colouring:

![image](https://github.com/user-attachments/assets/e08dea51-d177-4007-9926-bd72fbfcc955)

So that hopefully gives a preview to what could be soon in Zed.

Having a quick look at this repo, it seems that the tree-sitter query files have been copied over from https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/latex (presumably to be adjusted at some point).
These will need adjusting, in particular the way language injections are done in Zed [is slightly differently](https://zed.dev/blog/syntax-aware-editing#multi-language-documents) to neovim.

So I imagine the colouring will be rich soon, I am also personally invested like you so I may submit a PR at some point.

**Comment by lnay** [comment]
The other end of the issue is that colour themes (independent of this extension), need to define colours for the highlight items that this extension has queries for.

For example the `@markup.math` is used for mathmode content but it looks like the "colorizer" theme (seems to be default in my install) does not specify a colour for it.

The "tree-sitter compatible" neovim colour schemes have had a few years to mature and implement colours for the common tree-sitter grammars, but it looks like the zed themes have not yet.

**Comment by lnay** [comment]
Looking at your example closer, patching an existing colour theme to add colours for a few capture groups such an `spell`, `nospell`, `markup.mathmode`, ... gives a much better look:

![image](https://github.com/user-attachments/assets/70e55d4c-37ae-484c-b0b4-9b6b4d3ba997)

So this is really all down to waiting for the themes to catch up on this. I've submitted a [PR](https://github.com/rzukic/zed-latex/pull/4) to fix the language injection issue, but I think that's the only "issue" with *this* repo.

**Comment by ivansigmund** [comment]
> @ivansigmund If you want to try this out now you can install the "KTRZ Monokai Theme" extension and replace the following file (this is the location on linux): `~/.local/share/zed/extensions/installed/ktrz-monokai/themes/ktrz-monokai.json`
> 
> with this attachment: [ktrz-monokai.json](https://github.com/user-attachments/files/16253821/ktrz-monokai.json)

it's working! thank you so much! i understand now!

**Comment by lnay** [comment]
I think the situation is different to what I said earlier now that Zed have
released some sort of "official" list of [captures for highlighting](https://zed.dev/docs/extensions/languages#syntax-highlighting). This may have existed before, but I hadn't seen it until recently.

Even in neovim, where those capture groups are used (such as `markup.math`), there is no highlighting in any of the pre-installed colourschemes. So I think that the highlight captures in this extension should target the list linked above.
I'm suggesting this in \#8.
