### ISSUE TITLE
Language server does not show up

### ISSUE THREAD

**Issue by frankier** [rzukic/zed-latex#36]
I have a file open with filetype `LaTeX`, however `texlab` doesn't show up in the language server's logs and there are no actions.

Thing I've tired are downloading and building texlab and configuring it with:

```
...
  "lsp": {
    "texlab": {
      "binary": {
        "path": "/path/to/texlab/target/release/texlab",
      }}}
....
```

And trying to make the association myself:

```
  "languages": {
    "LaTeX": {
      "language_servers": ["texlab"]
    }
  },
```

This is with Zed 0.161.2 on Debian bookworm. Syntax highlighting is working fine.

ETA: This is with zed-latex 0.11. I tried installing as a dev extension from github but I couldn't get this working (nothing seems to happen?)

**Comment by lnay** [comment]
I happen to be online... 
Can you copy the section of the Zed log about launching texlab?

Extra info:
- arch (x64?)
- Did you try opening a latex file without any extra config? Do you need to manage the texlab install yourself instead of letting the extension install/update?

**Comment by lnay** [comment]
This is what a correct start of `texlab` will look like in the Zed log:

https://github.com/user-attachments/assets/eaace708-3a1a-425e-a6ea-90beda75d5ee

**Comment by frankier** [comment]
Yes x64.

Mostly I was trying as non-dev.

I don't see anything like that. If you send me a "known good" file I will remove all config and post you the full Zed log.

It's possible this is a Zed problem. I guess extensions could be janky and there are silent/unlogged failures of some kind. Any idea how to blast away all extension state?

**Comment by lnay** [comment]
Everything should work fine even with an empty/default `settings.json`. Can I confirm that this is a `.tex` file and not syntax injection within another syntax? If so, this is starting to feel like it might be a Zed/environment issue, but this is unlikely to be noticed by the Zed team before the issue is narrowed down more. I quickly tried a Debian 12 VM and I couldn't replicate this issue.

The way "texlab" doesn't appear in the Zed logs, not even an error makes it look as if the extension just isn't there (or Zed never asks the extension for the command to launch texlab).
This is the expected Zed log with no special config (the extension download texlab):
```
2024-11-15T22:28:44.50190598Z [INFO] starting language server process. binary path: "/home/luke/.local/share/zed/extensions/work/latex/texlab-v5.21.0/texlab", working directory: "/home/luke/Documents/repos/s1511002_gitlab/test", args: []
```
... and specifying a path of a `texlab` executable also gives the some kind of INFO log.

This is what happens when the settings specify a path that does not exist:

![image](https://github.com/user-attachments/assets/5894b6c5-078e-4d54-ac28-650a21d1f19a)

with this is the Zed log:
 ```
2024-11-15T22:30:49.133654809Z [INFO] attempting to start language server "texlab", path: "/home/luke/Documents/repos/s1511002_gitlab/test", id: 4
2024-11-15T22:30:49.133814591Z [INFO] starting language server process. binary path: "/home/luke/.cargo/bin/texlab", working directory: "/home/luke/Documents/repos/s1511002_gitlab/test", args: []
2024-11-15T22:30:49.135181777Z [ERROR] Failed to start language server "texlab": failed to spawn command. path: "/home/luke/.cargo/bin/texlab", working directory: "/home/luke/Documents/repos/s1511002_gitlab/test", args: []
```

This is achieved with settings like this:
```jsonc
{
  "lsp": {
    "texlab": {
      "binary": {
        "path": "/home/luke/.cargo/bin/texlab",
        "arguments": []
      },
// ...
}
```
Here are some more things to check:

The extensions page should look like this after normal install:
![image](https://github.com/user-attachments/assets/4bb98dc8-d090-4a8e-ad31-1b13caa1960d)

or like this as a dev extension (I think diagnosing non-dev is better to avoid variables):
![image](https://github.com/user-attachments/assets/8c0cdcd1-7e50-467e-9004-dcfa6c9e72d3)

Do language servers from other extensions work fine?

The extension should be found at `/home/luke/.local/share/zed/extensions/installed/latex/` and I believe the only "state" that keeps between Zed launches should be the contents of `~/.local/share/zed/extensions/work/latex/` which is where `texlab` executables are downloaded to.

**Comment by lnay** [comment]
Just had a thought: how did you install zed?

**Comment by frankier** [comment]
Hi. I tried again with a very simple LaTeX document and same thing. I also tried manually removing the directly and reinstalling and that didn't work.

Yes other language servers start.

I installed using `https://zed.dev/install.sh` (which I definitely manually audited first ho ho).

Here's a bit of extra investigation:

```
frankier ~/scratch [base] % ls -l ~/.local/share/zed/extensions/installed/latex/extension.wasm
-rw-r--r-- 1 frankier frankier 400818 Nov 18 22:52 /home/frankier/.local/share/zed/extensions/installed/latex/extension.wasm
frankier ~/scratch [base] % cat ~/.local/share/zed/extensions/installed/latex/extension.toml
id = "latex"
name = "LaTeX"
version = "0.1.2"
schema_version = 1
description = "LaTeX language server and syntax highlighting for Zed. See wiki on GitHub for help."
repository = "https://github.com/rzukic/zed-latex"
authors = ["Ruben Zukic <ruben@zukic.net>", "Oli Callaghan <me@olicallaghan.com>", "Luke Naylor <luke.naylr@gmail.com>"]
themes = []
languages = ["languages/latex", "languages/bibtex"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.bibtex]
repository = "https://github.com/latex-lsp/tree-sitter-bibtex"
rev = "ccfd77db0ed799b6c22c214fe9d2937f47bc8b34"

[grammars.latex]
repository = "https://github.com/latex-lsp/tree-sitter-latex"
rev = "a6c812704b3d3e1541b0853aa0d6d561301320e1"

[language_servers.texlab]
language = "LaTeX"
languages = []

[language_servers.texlab.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
```

Why is languages set to []? Could the problem be that the language server is never associated with latex files?

**Comment by lnay** [comment]
> Why is languages set to []? Could the problem be that the language server is never associated with latex files?

I'm not certain, that section seems to be autogenerated. The contents of your `extension.toml` are identical to mine though when I install.

I've run out of ideas and still can't find a cause or way to reproduce this so all I can do is give random suggestions.
- You could try editing `language` and `languages` in that file with different combinations of "latex" and "LaTeX"?
- You could try `grep texlab ~/.local/share/zed/logs/Zed.log` after each Zed restart (opening a tex file) to see if it ever shows up.
