### ISSUE TITLE
Disable window refocus after recompiling

### ISSUE THREAD

**Issue by korbiniak** [rzukic/zed-latex#45]
Hey there, is it somehow possible to stop the zed window from focusing to the pdf viewer after compilation? It's quite frustrating I have to go back to zed window every time this happens. I use okular, if this makes any difference. My config:

```
  "lsp": {
    "texlab": {
      "settings": {
        "texlab": {
          "build": {
            "onSave": true
          }
        }
      }
    }
  }
```

**Comment by lnay** [comment]
You can set "texlab.build.forwardSearchAfter" to false to stop that (at the cost of not having forwards search). The behaviour with window focusing will depend on the PDF viewer. Which one do you use? I'll check if there are any cli args which prevent this.

There is an alternative method of using Zed tasks to bind the forward search to a shortcut instead of relying on `texlab`, but it would have to be manually set up at the moment (I believe there's examples in the wiki).

**Comment by korbiniak** [comment]
Thanks, I thought that setting "texlab.build.forwardSearchAfter" did not work the first time I tried it. However it seems to be working, thank you so much!

**Comment by lnay** [comment]
With that setting turned off, it won't open the first time but editing the settings whilst the language server is running will still register the change, so you could turn it off after the first build.

Since okular doesn't take inverse search arguments from the cli, there's less of a benefit of relying on the auto config. If you value inverse search but not forwards as much, you can just open the PDF manually. Inverse search needs to be set up through okular settings anyway.

**Comment by lnay** [comment]
Can you try these settings please:
```jsonc
{
   "lsp": {
       "texlab": {
          "build": {
            "onSave": true,
            "forwardSearch": true
          },
          "forwardSearch": {
            "executable": "okular",
            "args": [
              "--unique",
              "--noraise", // difference from auto config here
              "file:%p#src:%l%f"
            ]
          }
      }
   }
}
```

For me (okular in gnome) the window does not focus after forward searching with or without the "--noraise", but it might be different in KDE (is that what you are using?).

I also don't seem to have forward search working at all.
You can also try this which might get inverse search working too without touching okular settings:
```jsonc
          "forwardSearch": {
            "executable": "okular",
            "args": [
              "--unique",
              "--noraise",
              "--editor-cmd",
              "\"zed '%f':%l:%c\"", // maybe 'zeditor' instead here if you installed via the package manager
              "file:%p#src:%l%f"
            ]
          }
```

Let me know what works with which settings for you and the auto config might get adjusted. I'm starting to have a feeling that okular isn't fully functional outside of KDE.

**Comment by korbiniak** [comment]
First of all, thanks for diving deeper into this! I tried both settings and none of them forward search, but the refocus does not occur, so thank you for that.

I'm using i3 with okular, I might try another pdf viewer.

**Comment by lnay** [comment]
Didn't see those edits, it seems this stuff is definitely desktop environment dependent.

For Edit2: zathura watches for changes in the PDF document, maybe the reloads are making i3 refocus that window even without texlab constantly calling the forward search command.

One random thing to test would be the `--fork` argument to `zathura`, which is really about processes but might possibly have a knock-on effect on the behaviour of the window.

**Comment by lnay** [comment]
> Edit2: refocusing and forwad search happens even with forwardSearch set to false.

I realise there was actually a typo above, it should be:
```jsonc
{
   "lsp": {
       "texlab": {
          "build": {
            "onSave": true,
            "forwardSearchAfter": true                 // not "forwardSearch"
          },
          "forwardSearch": {                                  // this is indeed "forwardSearch"
            "executable": "okular",
            "args": [
              "--unique",
              "--noraise", // difference from auto config here
              "file:%p#src:%l%f"
            ]
          }
      }
   }
}
```
